[general]
#import = [ "./themes/thinker.toml"]

[window]
decorations = "None"
blur = true
opacity = 0.7

[font]
normal = { family = "JetBrainsMono NF", style = "Regular" }
bold = { style = "Bold"}

[cursor]
style = { shape = "Block", blinking = "On"}

[mouse]
hide_when_typing = true
