full_screen_fg = "#faf7f2"
full_screen_bg = "#2c2a24"

gradient_color = ["#bd3131", "#31bd38"]

file_panel_fg = "#fbad30"
file_panel_bg = "#2c2a24"
file_panel_border = "#fbad30"
file_panel_border_active = "#4a9191"
file_panel_top_directory_icon = "#fbad30"
file_panel_top_path = "#faf7f2"
file_panel_item_selected_fg = "#4a9191"
file_panel_item_selected_bg = "#2c2a24"

footer_fg = "#fbad30"
footer_bg = "#2c2a24"
footer_border = "#fbad30"
footer_border_active = "#fac269"

sidebar_fg = "#fbad30"
sidebar_bg = "#2c2a24"
sidebar_title = "#faf7f2"
sidebar_border = "#fbad30"
sidebar_border_active = "#4a9191"
sidebar_item_selected_fg = "#4a9191"
sidebar_item_selected_bg = "#2c2a24"
sidebar_divider = "#fbad30"

modal_fg = "#fbad30"
modal_bg = "#2c2a24"
modal_border_active = "#fac269"
modal_cancel_fg = "#2c2a24"
modal_cancel_bg = "#bd3131"
modal_confirm_fg = "#2c2a24"
modal_confirm_bg = "#31bd38"

help_menu_hotkey = "#403e39"
help_menu_title = "#fbad30"

cursor = "#faf7f2"
correct = "#31bd38"
error = "#bd3131"
hint = "#d4c7c7"
cancel = "#bd3131"
